//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KetNoi_CSDL.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class NHANVIEN
    {
        [Required(ErrorMessage = "Mã nhân viên không được để trống")]
        public string Manv { get; set; }

        [Required(ErrorMessage = "Tên nhân viên không được dể trống")]
        public string Hoten { get; set; }

        [Required(ErrorMessage ="Bạn phải chọn mã phòng")]
        public string Maphong { get; set; }

        [Required(ErrorMessage ="Lương không được đẻ trống")]
        [Range(0, double.MaxValue, ErrorMessage = "Lương phải là số dương")]
        public Nullable<double> Luong { get; set; }

        public virtual PHONG PHONG { get; set; }
        public string TenPhong => PHONG != null ? PHONG.Tenphong : "";
    }
}
